config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  get 'home/index'

  get "home/charts_datas"
  get "home/charts_datas_comparable"
  get "home/charts_datas_normalized"

  get "home/todays_report"
  
  post "home/calculate_notional_buy"

  resources :stock_exchanges
  resources :stock_exchange_daily_closing_prices
  resources :shares do
    get 'notional_buy_by_quantity_inline', :on => :member
    get 'notional_buy_by_investment_inline', :on => :member
    get 'notional_buy_by_price_inline', :on => :member
    get 'charts_data', :on => :member
    get 'charts_historical_data', :on => :member
    get 'charts_datas', :on => :collection
  end
  resources :portfolio_changes
  resources :identifiers
  resources :daily_closing_prices do
      get 'new_multiple', :on => :collection
      post 'create_multiple', :on => :collection
      get 'edit_inline', :on => :member
      put 'update_inline', :on => :member
  end

end

app/models/portfolio_change.rb
class PortfolioChange < ActiveRecord::Base
  belongs_to :share

  has_one :first_buy, -> { where("transaction_type = 'buy'").order('`date_of_day` ASC') }, class_name: 'PortfolioChange'

  def total_value
    quantity * price_per_share
  end

  def value_of_taxes_absolute
    - ( total_cost_of_order + total_value )
  end

  def value_of_taxes_in_percent
    if total_value != 0
      value_of_taxes_absolute / ( total_value / 100 )
    else
      0
    end
  end

end

app/controllers/portfolio_changes_controller.rb
class PortfolioChangesController < ApplicationController
  before_action :set_portfolio_change, only: [:show, :edit, :update, :destroy]

  # GET /portfolio_changes
  # GET /portfolio_changes.json
  def index
    @portfolio_changes = PortfolioChange.all
  end

  # GET /portfolio_changes/1
  # GET /portfolio_changes/1.json
  def show
  end

  # GET /portfolio_changes/new
  def new
    @portfolio_change = PortfolioChange.new
  end

  # GET /portfolio_changes/1/edit
  def edit
  end

  # POST /portfolio_changes
  # POST /portfolio_changes.json
  def create
    @portfolio_change = PortfolioChange.new(portfolio_change_params)

    respond_to do |format|
      if @portfolio_change.save
        format.html { redirect_to @portfolio_change, notice: 'Portfolio change was successfully created.' }
        format.json { render :show, status: :created, location: @portfolio_change }
      else
        format.html { render :new }
        format.json { render json: @portfolio_change.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portfolio_changes/1
  # PATCH/PUT /portfolio_changes/1.json
  def update
    respond_to do |format|
      if @portfolio_change.update(portfolio_change_params)
        format.html { redirect_to @portfolio_change, notice: 'Portfolio change was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio_change }
      else
        format.html { render :edit }
        format.json { render json: @portfolio_change.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolio_changes/1
  # DELETE /portfolio_changes/1.json
  def destroy
    @portfolio_change.destroy
    respond_to do |format|
      format.html { redirect_to portfolio_changes_url, notice: 'Portfolio change was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio_change
      @portfolio_change = PortfolioChange.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portfolio_change_params
      params.require(:portfolio_change).permit(:share_id, :transaction_type, :quantity, :price_per_share, :total_cost_of_order, :date_of_day)
    end
end

app/helpers/portfolio_changes_helper.rb
module PortfolioChangesHelper
end

app/views/portfolio_changes/_form.html.erb
<%= form_for(@portfolio_change) do |f| %>
  <% if @portfolio_change.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@portfolio_change.errors.count, "error") %> prohibited this portfolio_change from being saved:</h2>

      <ul>
      <% @portfolio_change.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date_of_day %><br>
    <%= f.date_select :date_of_day %>
  </div>
  <div class="field">
    <%= f.label :share %><br>
    <%= collection_select(:portfolio_change, :share_id, Share.all, :id, :name_isin) %>
    <%= link_to "Create new Share", new_share_path %>
  </div>
  <div class="field">
    <%= f.label :transaction_type %><br>
    <%= f.select :transaction_type, ['buy', 'sell'] %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :price_per_share %><br>
    <%= f.text_field :price_per_share %>
  </div>
  <div class="field">
    <%= f.label :total_cost_of_order %><br>
    <%= f.text_field :total_cost_of_order %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/portfolio_changes/edit.html.erb
<h1>Editing Portfolio Change</h1>

<%= render 'form' %>

<%= link_to 'Show', @portfolio_change %> |
<%= link_to 'Back', portfolio_changes_path %>

app/views/portfolio_changes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Portfolio Changes</h1>

<table>
  <thead>
    <tr>
      <th>Date of Day</th>
      <th>Share</th>
      <th>Transaction type</th>
      <th>Quantity</th>
      <th>Price per share</th>
      <th>Total cost of order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @portfolio_changes.each do |portfolio_change| %>
      <tr>
        <td><%= portfolio_change.date_of_day %></td>
        <td><%= link_to portfolio_change.share.name_isin, portfolio_change.share %></td>
        <td><%= portfolio_change.transaction_type %></td>
        <td><%= portfolio_change.quantity %></td>
        <td><%= number_to_currency portfolio_change.price_per_share, :unit => portfolio_change.share.currency, :precision => 3 %></td>
        <td><%= number_to_currency portfolio_change.total_cost_of_order, :unit => portfolio_change.share.currency, :precision => 2 %></td>
        <td><%= link_to 'Show', portfolio_change %></td>
        <td><%= link_to 'Edit', edit_portfolio_change_path(portfolio_change) %></td>
        <td><%= link_to 'Destroy', portfolio_change, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Portfolio change', new_portfolio_change_path %>

app/views/portfolio_changes/new.html.erb
<h1>New Portfolio Change</h1>

<%= render 'form' %>

<%= link_to 'Back', portfolio_changes_path %>

app/views/portfolio_changes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Share:</strong>
  <%= link_to @portfolio_change.share.name_isin, @portfolio_change.share %>
</p>

<p>
  <strong>Transaction type:</strong>
  <%= @portfolio_change.transaction_type %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @portfolio_change.quantity %>
</p>

<p>
  <strong>Price per share:</strong>
  <%= @portfolio_change.price_per_share %>
</p>

<p>
  <strong>Total cost of order:</strong>
  <%= @portfolio_change.total_cost_of_order %>
</p>

<p>
  <strong>Date of Day:</strong>
  <%= @portfolio_change.date_of_day %>
</p>

<%= link_to 'Edit', edit_portfolio_change_path(@portfolio_change) %> |
<%= link_to 'Back', portfolio_changes_path %>