config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  get 'home/index'

  get "home/charts_datas"
  get "home/charts_datas_comparable"
  get "home/charts_datas_normalized"

  get "home/todays_report"
  
  post "home/calculate_notional_buy"

  resources :stock_exchanges
  resources :stock_exchange_daily_closing_prices
  resources :shares do
    get 'notional_buy_by_quantity_inline', :on => :member
    get 'notional_buy_by_investment_inline', :on => :member
    get 'notional_buy_by_price_inline', :on => :member
    get 'charts_data', :on => :member
    get 'charts_historical_data', :on => :member
    get 'charts_datas', :on => :collection
  end
  resources :portfolio_changes
  resources :identifiers
  resources :daily_closing_prices do
      get 'new_multiple', :on => :collection
      post 'create_multiple', :on => :collection
      get 'edit_inline', :on => :member
      put 'update_inline', :on => :member
  end

end

app/models/share.rb
class Share < ActiveRecord::Base
  belongs_to :stock_exchange

  has_many :daily_closing_prices
  has_many :identifiers
  has_many :portfolio_changes

  has_one :last_daily_closing_price, -> { order('daily_closing_prices.date_of_day DESC') }, class_name: 'DailyClosingPrice'
  has_one :max_daily_closing_price, -> { order('daily_closing_prices.price DESC') }, class_name: 'DailyClosingPrice'
  has_one :min_daily_closing_price, -> { order('daily_closing_prices.price ASC') }, class_name: 'DailyClosingPrice'

  def name_isin
    return "".concat(name.to_s).concat(" (").concat(isin.to_s).concat(")")
  end

  def self.sorted_by_name_isin
    Share.all.sort_by(&:name_isin)
  end

  def portfolio_sums
    portfolio_sums_by_date( Time.now )
  end

  def portfolio_sums_by_date( time )
    # SELECT
    #     `share_id`,
    #     SUM(`quantity`) as `total_quatity`,
    #     SUM(`price_per_share`*`quantity`)/SUM(`quantity`) as `average_price_per_share`,
    #     SUM(`total_cost_of_order`)  as `total_cost_of_orders`
    # FROM `portfolio_changes`
    # WHERE `date_of_day` <= <time>
    # GROUP BY share_id
    @portfolio_sums = {
      :total_quantity => 0,
      :average_price => 0,
      :total_price => 0,
      :total_cost_of_orders => 0
    }
    portfolio_changes.each { |pc|
      if pc.date_of_day <= time.to_date
        @portfolio_sums[:total_quantity] += pc.quantity
        @portfolio_sums[:total_price] += pc.price_per_share * pc.quantity
        @portfolio_sums[:total_cost_of_orders] += pc.total_cost_of_order
      end
    }
    if @portfolio_sums[:total_quantity] > 0
      @portfolio_sums[:average_price] = @portfolio_sums[:total_price] / @portfolio_sums[:total_quantity]
    else
      @portfolio_sums[:average_price] = 0
    end
    @portfolio_sums
  end


  def historical_prices
      _historical_prices_from(DateTime.new.to_date)
  end

  def historical_prices_from(date)
    _historical_prices_from(date)
  end

  def last_closing_price
    last_daily_closing_price
  end
  
  def max_daily_closing_price_since(date)
    daily_closing_prices.where("`daily_closing_prices`.`date_of_day` > '"+date.to_s+"'").order("price DESC").first
  end

  def min_daily_closing_price_since(date)
    daily_closing_prices.where("`daily_closing_prices`.`date_of_day` > '"+date.to_s+"'").order("price ASC").first
  end

  def relation_current_value_to_costs_in_percent
    if !last_closing_price.nil? then
      last_closing_price.price / (portfolio_sums[:average_price] / 100)
    else
      0
    end
  end

  def last_total_value
    if !last_closing_price.nil? then
      portfolio_sums[:total_quantity] * last_closing_price.price
    else
      0
    end
  end

  def previous_total_value
    if !last_closing_price.nil? && !last_closing_price.previous.nil? then
      portfolio_sums[:total_quantity] * last_closing_price.previous.price
    else
      0
    end
  end

  def profit_or_lost_by_current_share_price
    last_total_value - portfolio_sums[:total_price]
  end

  def profit_or_lost_by_total_costs
    last_total_value + portfolio_sums[:total_cost_of_orders]
  end

  def notional_buy
    #NotionalBuy.new( self, total_price_normalised_to_500_tranches )
    #notional_buy_by_quantity( total_price_normalised_to_500_tranches )
    notional_buy_by_investment_of( total_price_normalised_to_500_tranches )
  end

  def notional_buy_by_investment_of( investment = 0 )
    return NotionalBuy.new( self, investment.to_i, nil )
  end

  def notional_buy_by_quantity( quantity = 0 )
    NotionalBuy.new( self, (quantity.to_i * last_closing_price.price).ceil, nil )
  end
  
  def notional_buy_by_price( investment = 0, quantity = 0, price = 0.0 )
    if investment.nil? || investment == 0
      puts "calculating by quantity"
      puts price.to_f
      NotionalBuy.new( self, (quantity.to_i * price.to_f), price.to_f )
    else
      puts "calculating by investment"
      puts price.to_f
      NotionalBuy.new( self, investment.to_i, price.to_f )
    end
  end

  ### Notional buy:
  class NotionalBuy

    @share = nil
    @total_price_of_investment = nil
    @share_price_for_investment = nil
    # @quantity = nil
    # @total_price = nil
    # @price_per_share = nil
    # @change_of_average_price_in_currency = nil
    # @change_of_average_price_in_percent = nil
    # @quantity_after = nil
    # @total_value_after = nil
    # @difference_of_total_price_to_total_value = nil

    

    def initialize( share, total_price_of_investment, share_price_for_investment )
      @share = share
      @total_price_of_investment = total_price_of_investment.to_i
      if share_price_for_investment.nil? && !@share.last_closing_price.nil?
        @share_price_for_investment = @share.last_closing_price.price
      else
        @share_price_for_investment = share_price_for_investment.to_f
      end
      
      #puts "###"
      #puts self.inspect
      #puts "###"
      
      # @quantity = quantity
      # @total_price = total_price
      # @price_per_share = price_per_share
      # @change_of_average_price_in_currency = change_of_average_price_in_currency
      # @change_of_average_price_in_percent = change_of_average_price_in_percent
      # @quantity_after = quantity_after
      # @total_value_after = total_value_after
      # @difference_of_total_price_to_total_value = difference_of_total_price_to_total_value
    end

    def share
      @share
    end
    
    def share_price_for_investment
      @share_price_for_investment.to_f
    end

    def total_price_of_investment
      @total_price_of_investment
    end

    def quantity
      if @share_price_for_investment != 0 then
        @quantity = ( @total_price_of_investment / @share_price_for_investment ).floor.to_i
      else
        @quantity = 0
      end
    end
  
    def total_price
      @total_price = @share_price_for_investment * quantity
    end 
  
    def price_per_share
      if ( quantity + @share.portfolio_sums[:total_quantity] ) != 0
        @price_per_share = ( quantity * @share_price_for_investment + @share.portfolio_sums[:total_quantity] * @share.portfolio_sums[:average_price] ) / ( quantity + @share.portfolio_sums[:total_quantity] )
      else
        0
      end
    end
  
    def change_of_average_price_in_currency
      @change_of_average_price_in_currency = price_per_share - @share.portfolio_sums[:average_price]
    end
  
    def change_of_average_price_in_percent
      if @share.portfolio_sums[:average_price] != 0 then
        @change_of_average_price_in_percent = price_per_share / ( @share.portfolio_sums[:average_price] / 100 ) - 100
      else
        0
      end
    end
    
    def quantity_after
      @quantity_after = ( quantity + @share.portfolio_sums[:total_quantity] ).to_i
    end
  
    def total_value_after
      @total_value_after = quantity_after * @share_price_for_investment
    end
  
    def difference_of_total_price_to_total_value
      @difference_of_total_price_to_total_value = total_value_after - ( @share.portfolio_sums[:total_price] + total_price )
    end

  end
  ### /Notional buy

  private
    def total_price_normalised_to_500_tranches
      (portfolio_sums[:total_price] / 500).ceil * 500
    end

    def _historical_prices_from(date)
      @historical_prices = []
      # logger.debug "dailyClosingPrice hash: #{d.inspect}" || 
      daily_closing_prices.find_all{ |d| d.date_of_day >= date }.sort_by { |sds| sds.date_of_day }.each { |dcp|
        historic_portfolio_sum = portfolio_sums_by_date( dcp.date_of_day )
        @historical_prices.push(
          {
            :date_of_day => dcp.date_of_day,
            :total_market_value => historic_portfolio_sum[:total_quantity] * dcp.price,
            :total_win => (historic_portfolio_sum[:total_quantity] * dcp.price) - (historic_portfolio_sum[:total_quantity] * historic_portfolio_sum[:average_price]),
            :total_price => historic_portfolio_sum[:total_price]
          }
        )
      }
      @historical_prices
    end

end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
  before_action :set_share, only: [:show, :edit, :update, :destroy, :charts_data, :charts_historical_data ]

  # GET /shares
  # GET /shares.json
  def index
    @shares = Share.all
  end

  # GET /shares/1
  # GET /shares/1.json
  def show
  end

  # GET /shares/new
  def new
    @share = Share.new
  end

  # GET /shares/1/edit
  def edit
  end

  # POST /shares
  # POST /shares.json
  def create
    @share = Share.new(share_params)

    respond_to do |format|
      if @share.save
        format.html { redirect_to @share, notice: 'Share was successfully created.' }
        format.json { render :show, status: :created, location: @share }
      else
        format.html { render :new }
        format.json { render json: @share.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shares/1
  # PATCH/PUT /shares/1.json
  def update
    respond_to do |format|
      if @share.update(share_params)
        format.html { redirect_to @share, notice: 'Share was successfully updated.' }
        format.json { render :show, status: :ok, location: @share }
      else
        format.html { render :edit }
        format.json { render json: @share.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shares/1
  # DELETE /shares/1.json
  def destroy
    @share.destroy
    respond_to do |format|
      format.html { redirect_to shares_url, notice: 'Share was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  # GET /shares/1/notional_buy_by_investment_inline
  def notional_buy_by_investment_inline
    @_share = Share.find(params[:share][:id])
    @notional_buy = @_share.notional_buy_by_investment_of(params[:share][:notional_buy_by_investment_of])
    respond_to do |format|
      format.json
    end
  end

  # GET /shares/1/notional_buy_by_quantity_inline
  def notional_buy_by_quantity_inline
    @_share = Share.find(params[:share][:id])
    @notional_buy = @_share.notional_buy_by_quantity(params[:share][:notional_buy_by_quantity])
    respond_to do |format|
      format.json { render "notional_buy_by_investment_inline" }
    end
  end

  # GET /shares/1/notional_buy_by_price_inline
  def notional_buy_by_price_inline
    @_share = Share.find(params[:share][:id])
    if params[:notional_buy_calculation_type] == "with_investment_of"
      puts self.class.to_s + " param.price: " + self.toCalculatableNumeric(params[:share][:notional_buy_by_price])
      @notional_buy = @_share.notional_buy_by_price(self.toCalculatableNumeric(params[:share][:notional_buy_by_investment_of]), 0, self.toCalculatableNumeric(params[:share][:notional_buy_by_price]).to_f)
    else
      puts self.class.to_s + " params.price: " + self.toCalculatableNumeric(params[:share][:notional_buy_by_price])
      @notional_buy = @_share.notional_buy_by_price(0, params[:share][:notional_buy_by_quantity], self.toCalculatableNumeric(params[:share][:notional_buy_by_price]).to_f)
    end
    respond_to do |format|
      format.json { render "notional_buy_by_investment_inline" }
    end
  end

  # get /shares/1/charts_data
  def charts_data
    @daily_closing_prices = @share.daily_closing_prices.sort{ |d1, d2| d1.date_of_day <=> d2.date_of_day }
    @stock_exchange = @share.stock_exchange
    @stock_exchange_daily_closing_prices = @stock_exchange.stock_exchange_daily_closing_prices.sort{ |d1,d2| d1.date_of_day <=> d2.date_of_day }
    respond_to do |format|
      format.json
    end
  end

  # get /shares/1/charts_historical_data
  def charts_historical_data
    @portfolio_changes = @share.portfolio_changes.sort { |pc1,pc2| pc1.date_of_day <=> pc2.date_of_day }
    @historical_prices = @share.historical_prices
    #@historical_total_prices = [] << { :date_of_day => Date.parse("2008-10-01"), :total_price => 0 }

    @historical_total_prices = []
    current_share_buy_price = 0
    @historical_prices.each { |hp|
      @pc_date_of_day_hp_date_of_day = @portfolio_changes.select { |pc| hp[:date_of_day] > pc.date_of_day }.last
      if @pc_date_of_day_hp_date_of_day != nil
        current_share_buy_price = @pc_date_of_day_hp_date_of_day.share.portfolio_sums_by_date( @pc_date_of_day_hp_date_of_day.date_of_day.to_time )[:total_price]
      end
      @historical_total_prices << { :date_of_day => hp[:date_of_day], :total_price => current_share_buy_price }
    }
    respond_to do |format|
      format.json
      format.html { render :layout => false    }
    end
  end

  # get /shares/charts_datas
  def charts_datas
    @datas = Array.new
    shares = Share.sorted_by_name_isin
    shares.each do |share|
      @datas << { :share => share, :daily_closing_prices => share.daily_closing_prices.order( :date_of_day ) }
    end
    respond_to do |format|
      format.json
      #format.json { render :json => @datas }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_share
      @share = Share.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def share_params
      params.require(:share).permit(:isin, :name, :currency, :stock_exchange_id)
    end
end

app/helpers/shares_helper.rb
module SharesHelper
end

app/views/shares/_form.html.erb
<%= form_for(@share) do |f| %>
  <% if @share.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@share.errors.count, "error") %> prohibited this share from being saved:</h2>

      <ul>
      <% @share.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :isin %><br>
    <%= f.text_field :isin %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :currency %><br>
    <%= f.text_field :currency %>
  </div>
  <div class="field">
    <%= f.label :stock_exchange %><br>
    <%= collection_select( :share, :stock_exchange_id, StockExchange.all, :id, :name ) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shares/_menu.html.erb
<ul>
	<% @shares.each do |share| %>
	<li><%= link_to share.name_isin, share %></li>
	<% end %>
</ul>

app/views/shares/charts_data.json.erb
{
  "title": {
    "text": "<%= @share.name %> Tagesschlusskurse"
  },
  "yAxis": [
    {
      "title": {
        "text": "Kurs der Aktie in EUR",
        "style": {
          "color": "#AA4643"
        }
      }
    },
    {
      "title": {
        "text": "Kurs des Index in 100 EUR",
        "style": {
          "color": "#4572A7"
        }
      }
    }
  ],
  "series": [
    {
      "name": "<%= @share.name %>",
      "data": [
        <% @daily_closing_prices.each_with_index do |daily_closing_price, idx| %>
            [ <%= daily_closing_price.date_of_day.to_time.utc.to_i * 1000 %>, <%= daily_closing_price.price.to_f %> ]<%= idx != @daily_closing_prices.length - 1 ? ',' : '' %>
        <% end %>
      ],
      "type": "line",
      "color": "#AA4643",
      "tooltip": {
        "yDecimals": 2,
        "pointFormat": "<span style=\"color:{series.color}\">{series.name}</span>: <b>{point.y} EUR</b><br/>"
      }
    },
    {
      "name": "<%= @stock_exchange.name %>",
      "data": [
        <% @stock_exchange_daily_closing_prices.each_with_index do |daily_closing_price, idx| %>
          [ <%= daily_closing_price.date_of_day.to_time.utc.to_i * 1000 %>, <%= daily_closing_price.price.to_f / 100 %> ]<%= idx != @stock_exchange_daily_closing_prices.length - 1 ? ',' : '' %>
        <% end %>
      ],
      "type": "area",
      "threshold": 0,
      "tooltip": {
        "yDecimals": 2,
        "pointFormat": "<span style=\"color:{series.color}\">{series.name}</span>: <b>{point.y} * 100</b><br/>"
      },
      "color": "#4572A7",
      "fillColor": {
        "linearGradient": {
          "x1": 0,
          "y1": 0,
          "x2": 0,
          "y2": 1
        },
        "stops": [[0, "#4572A7"], [1, "rgba(0,0,0,0)"]]
      }
    }
  ]
}

app/views/shares/charts_datas.json.erb
{
  "title": {
    "text": "Tagesschlusskurse aller Aktien"
  },
  "legend": {
    "enabled": true
  },
  "series": [
    <%
      @datas.each_with_index do |data, d_idx|
        @share = data[:share]
        @daily_closing_prices = data[:daily_closing_prices]
    %>
    {
      "name": "<%= @share.name %>",
      "data": [
        <% @daily_closing_prices.each_with_index do |daily_closing_price, dcp_idx| %>
            [ <%= daily_closing_price.date_of_day.to_time.utc.to_i * 1000 %>, <%= daily_closing_price.price.to_f %> ]<%= dcp_idx != @daily_closing_prices.length - 1 ? ',' : '' %>
        <% end %>
      ],
      "tooltip": {
        "yDecimals": 2
      }
    }<%= d_idx != @datas.length - 1 ? ',' : '' %>
    <%
      end
    %>
  ]
}

app/views/shares/charts_historical_data.html.erb
<pre><code>
<%= @share.inspect %>

<%=@historical_prices.inspect %>

<%=@historical_total_prices.inspect %>

<%=@portfolio_changes.inspect %>

</code></pre>

app/views/shares/charts_historical_data.json.erb
{
  "title": {
    "text": "<%= @share.name %>: historischer Depotwert dieser Aktie"
  },
  "yAxis": [
    {
      "title": {
        "text": "Wert je Tag"
      }
    }
  ],
  "legend": {
    "enabled": true
  },
  "series": [
    {
      "name": "Wert des Bestands der<br /><%= @share.name %> Aktien im Depot",
      "id": "historical_prices",
      "data": [
        <% @historical_prices.each_with_index do |historical_price, idx| %>
            [ <%= historical_price[:date_of_day].to_time.utc.to_i * 1000 %>, <%= historical_price[:total_market_value].to_f %> ]<%= idx != @historical_prices.length - 1 ? ',' : '' %>
        <% end %>
      ]
    },
    {
      "name": "Kaufpreis",
      "id": "costs",
      "data": [
        <% @historical_total_prices.each_with_index do |htp, idx| %>
          [ <%= htp[:date_of_day].to_time.utc.to_i * 1000 %>, <%= htp[:total_price] %>]<%= idx != @historical_total_prices.length - 1 ? ',' : '' %>
        <% end %>
      ]
    },
    {
      "name": "Gewinn / Verlust",
      "id": "costs",
      "data": [
        <% @historical_prices.each_with_index do |htp, idx| %>
          [ <%= htp[:date_of_day].to_time.utc.to_i * 1000 %>, <%= htp[:total_win] %>]<%= idx != @historical_prices.length - 1 ? ',' : '' %>
        <% end %>
      ]
    },
    {
      "type": "flags",
      "name": "Käufe / Verkäufe",
      "showInLegend": false,
      "data": [
        <% @portfolio_changes.each_with_index do |portfolio_change, idx|  %>
        {
          "x": <%= portfolio_change.date_of_day.to_time.utc.to_i * 1000 %>,
          "title": "<%= portfolio_change.transaction_type == "buy" ? "K" : "V" %>",
          "text" : "<%= portfolio_change.transaction_type == "buy" ? "Kauf" : "Verkauf" %> von <%= portfolio_change.quantity %> Aktien für je <%= number_to_currency portfolio_change.price_per_share, :precision => 2, :unit => @share.currency %>"
        }<%= idx != @portfolio_changes.length - 1 ? ',' : '' %>
        <% end %>
      ],
      "onSeries": "costs",
      "shape": "circlepin",
      "width": 24
    }
  ]
}

app/views/shares/edit.html.erb
<h1>Editing Share</h1>

<%= render 'form' %>

<%= link_to 'Show', @share %> |
<%= link_to 'Back', shares_path %>

app/views/shares/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Shares</h1>

<table>
  <thead>
    <tr>
      <th>Isin</th>
      <th>Name</th>
      <th>Currency</th>
      <th>Stock exchange</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shares.each do |share| %>
      <tr>
        <td><%= share.isin %></td>
        <td><%= share.name %></td>
        <td><%= share.currency %></td>
        <td><%= link_to share.stock_exchange.name, share.stock_exchange %></td>
        <td><%= link_to 'Show', share %></td>
        <td><%= link_to 'Edit', edit_share_path(share) %></td>
        <td><%= link_to 'Destroy', share, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

<div id="shares_chart_container"></div>

<br />

<div id="shares_chart_container_compare"></div>

<br />

<%= link_to 'New Share', new_share_path %>

app/views/shares/new.html.erb
<h1>New Share</h1>

<%= render 'form' %>

<%= link_to 'Back', shares_path %>

app/views/shares/notional_buy_by_investment_inline.json.erb
{
	"rows": [
		"<%= number_to_currency @notional_buy.total_price_of_investment %>",
		"<%= @notional_buy.quantity %>",
		"<%= number_to_currency @notional_buy.total_price %>",
		"<%= number_to_currency @notional_buy.share_price_for_investment %>",
		"<%= number_to_currency @notional_buy.price_per_share %>",
		"<%= number_to_currency @notional_buy.change_of_average_price_in_currency %>",
		"<%= number_to_percentage @notional_buy.change_of_average_price_in_percent %>",
		"<%= @notional_buy.quantity_after %>",
		"<%= number_to_currency @notional_buy.total_value_after %>",
		"<%= number_to_currency @notional_buy.difference_of_total_price_to_total_value %>"
	]
}