config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  get 'home/index'

  get "home/charts_datas"
  get "home/charts_datas_comparable"
  get "home/charts_datas_normalized"

  get "home/todays_report"
  
  post "home/calculate_notional_buy"

  resources :stock_exchanges
  resources :stock_exchange_daily_closing_prices
  resources :shares do
    get 'notional_buy_by_quantity_inline', :on => :member
    get 'notional_buy_by_investment_inline', :on => :member
    get 'notional_buy_by_price_inline', :on => :member
    get 'charts_data', :on => :member
    get 'charts_historical_data', :on => :member
    get 'charts_datas', :on => :collection
  end
  resources :portfolio_changes
  resources :identifiers
  resources :daily_closing_prices do
      get 'new_multiple', :on => :collection
      post 'create_multiple', :on => :collection
      get 'edit_inline', :on => :member
      put 'update_inline', :on => :member
  end

end

app/views/shared/_menu.html.erb
<ul class="menu">
	<li><%= link_to 'Home', root_path %></li>
	<li>
		<%= link_to 'Aktien', shares_path %>
		<%= render "shares/menu" %>
	</li>
	<li><%= link_to 'Börsen', stock_exchanges_path %></li>
	<li><%= link_to 'Tagesschlusskurse', daily_closing_prices_path %></li>
	<li><%= link_to 'Tagesschlusskurse der Börsen', stock_exchange_daily_closing_prices_path %></li>
	<li><%= link_to 'Aktien-Käufe / -Verkäufe', portfolio_changes_path %></li>
	<li><%= link_to 'Andere Kennungen der Aktien', identifiers_path %></li>
</ul>