config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  get 'home/index'

  get "home/charts_datas"
  get "home/charts_datas_comparable"
  get "home/charts_datas_normalized"

  get "home/todays_report"
  
  post "home/calculate_notional_buy"

  resources :stock_exchanges
  resources :stock_exchange_daily_closing_prices
  resources :shares do
    get 'notional_buy_by_quantity_inline', :on => :member
    get 'notional_buy_by_investment_inline', :on => :member
    get 'notional_buy_by_price_inline', :on => :member
    get 'charts_data', :on => :member
    get 'charts_historical_data', :on => :member
    get 'charts_datas', :on => :collection
  end
  resources :portfolio_changes
  resources :identifiers
  resources :daily_closing_prices do
      get 'new_multiple', :on => :collection
      post 'create_multiple', :on => :collection
      get 'edit_inline', :on => :member
      put 'update_inline', :on => :member
  end

end

app/models/daily_closing_price.rb
class DailyClosingPrice < ActiveRecord::Base
  belongs_to :share

  validates_uniqueness_of :share_id, :scope => :date_of_day

  @previous = nil

  def previous
    if @previous.nil?
      #@previous = DailyClosingPrice.first(:conditions => ["daily_closing_prices.date_of_day < ? AND daily_closing_prices.share_id = ?", self.date_of_day, share_id], :order => "daily_closing_prices.date_of_day DESC", :limit => 1 )
      @previous = DailyClosingPrice.where("`date_of_day` < ? AND share_id = ?", self.date_of_day, share_id).order('`date_of_day` DESC').first;
    else
      @previous
    end
  end

  def change_to_previous_absolute
    if not previous.nil?
      - (previous.price - self.price)
    else
      "<N/A>"
    end
  end

  def change_to_previous_in_percent
    if not previous.nil?
      self.price / ( previous.price / 100 ) - 100
    else
      "<N/A>"
    end
  end

end

app/controllers/daily_closing_prices_controller.rb
class DailyClosingPricesController < ApplicationController
  before_action :set_daily_closing_price, only: [:show, :edit, :edit_inline, :update, :destroy]
  layout Proc.new { |controller| controller.request.xhr? ? 'xhr' : 'application' }

  # GET /daily_closing_prices
  # GET /daily_closing_prices.json
  def index
    @daily_closing_prices = DailyClosingPrice.all
    @shown_per_page = Share.all.size * 5
    @showing_from = (params[:page] != nil ? params[:page].to_i : 1) * @shown_per_page - @shown_per_page + 1
    @showing_to = (params[:page] != nil ? params[:page].to_i : 1) * @shown_per_page
    @daily_closing_prices = DailyClosingPrice.paginate( :page => params[:page], :per_page => @shown_per_page ).order( '`daily_closing_prices`.`date_of_day` DESC, `daily_closing_prices`.`share_id` ASC' ) #.sort_by { |dcp| dcp.share.name_isin }
  end

  # GET /daily_closing_prices/1
  # GET /daily_closing_prices/1.json
  def show
  end

  # GET /daily_closing_prices/new
  def new
    @daily_closing_price = DailyClosingPrice.new
  end

  def new_multiple
    @shares = Share.all.sort{|t1,t2|t1.name <=> t2.name}
    @daily_closing_prices = @shares.collect { |share| DailyClosingPrice.new( :share_id => share.id ) }
  end

  # GET /daily_closing_prices/1/edit
  def edit
  end

  # GET /daily_closing_prices/1/edit_inline
  def edit_inline
  end

  # POST /daily_closing_prices
  # POST /daily_closing_prices.json
  def create
    @daily_closing_price = DailyClosingPrice.new(daily_closing_price_params)

    respond_to do |format|
      if @daily_closing_price.save
        format.html { redirect_to @daily_closing_price, notice: 'Daily closing price was successfully created.' }
        format.json { render :show, status: :created, location: @daily_closing_price }
      else
        format.html { render :new }
        format.json { render json: @daily_closing_price.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /daily_closing_prices/1
  # PATCH/PUT /daily_closing_prices/1.json
  def update
    respond_to do |format|
      if @daily_closing_price.update(daily_closing_price_params)
        format.html { redirect_to @daily_closing_price, notice: 'Daily closing price was successfully updated.' }
        format.json { render :show, status: :ok, location: @daily_closing_price }
      else
        format.html { render :edit }
        format.json { render json: @daily_closing_price.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /daily_closing_prices/1
  # PUT /daily_closing_prices/1.json
  def update_inline

    respond_to do |format|
      if @daily_closing_price.update_attributes(params[:daily_closing_price])
        @notice = 'Daily closing price was successfully updated.'
        format.html #{ render, :notice => 'Daily closing price was successfully updated.' } # redirect_to @daily_closing_price,
        format.json { head :ok }
      else
        format.html { render :action => "edit_inline" }
        format.json { render :json => @daily_closing_price.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /daily_closing_prices/1
  # DELETE /daily_closing_prices/1.json
  def destroy
    @daily_closing_price.destroy
    respond_to do |format|
      format.html { redirect_to daily_closing_prices_url, notice: 'Daily closing price was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_daily_closing_price
      @daily_closing_price = DailyClosingPrice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def daily_closing_price_params
      params.require(:daily_closing_price).permit(:share_id, :price, :date_of_day)
    end
end

app/helpers/daily_closing_prices_helper.rb
module DailyClosingPricesHelper
end

app/views/daily_closing_prices/_form.html.erb
<%= form_for(@daily_closing_price) do |f| %>
  <% if @daily_closing_price.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@daily_closing_price.errors.count, "error") %> prohibited this daily_closing_price from being saved:</h2>

      <ul>
      <% @daily_closing_price.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :share_id %><br>
    <%= f.text_field :share_id %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :date_of_day %><br>
    <%= f.date_select :date_of_day %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/daily_closing_prices/create_multiple.html.erb
<h1>Listing daily_closing_prices</h1>

<p id="notice"><%= @notice %></p>

<table>
  <tr>
    <th>Share</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @daily_closing_prices.each do |daily_closing_price| %>
  <tr>
    <td><%= daily_closing_price.share.name %> (<%= daily_closing_price.share.isin %>)</td>
    <td><%= daily_closing_price.price %> <%=daily_closing_price.share.currency %></td>
    <td><%= daily_closing_price.when %></td>
    <td><%= link_to 'Show', daily_closing_price %></td>
    <td><%= link_to 'Edit', edit_daily_closing_price_path(daily_closing_price) %></td>
    <td><%= link_to 'Destroy', daily_closing_price, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Daily closing price', new_daily_closing_price_path %>
<!-- %= link_to 'New Daily closing prices', :controller => 'daily_closing_prices', :action => 'new_multiple' % -->
<%= link_to 'New Daily closing prices', :controller => 'daily_closing_prices', :action => 'new_multiple' %>

app/views/daily_closing_prices/edit.html.erb
<h1>Editing Daily Closing Price</h1>

<%= render 'form' %>

<%= link_to 'Show', @daily_closing_price %> |
<%= link_to 'Back', daily_closing_prices_path %>

app/views/daily_closing_prices/edit_inline.html.erb
<%= form_for(@daily_closing_price, :url => { :action => "update_inline" }, :html => { :class => 'xhr inlineform update' }) do |f| %>
<div class="field">
  <%= f.hidden_field :date_of_day %>
  <%= f.hidden_field :share_id %>
  <%= f.text_field :price %> €
</div>
<div class="actions">
	<%= submit_tag 's' %>
</div>
<% end %>

app/views/daily_closing_prices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Daily Closing Prices</h1>

<table>
  <thead>
    <tr>
      <th>Share</th>
      <th>Price</th>
      <th>Date of Day</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
<%
  displayed_date = nil
  table_row_css_class = "even"
  @daily_closing_prices.each do |daily_closing_price|
    if displayed_date != daily_closing_price.date_of_day
      displayed_date = daily_closing_price.date_of_day
      table_row_css_class = table_row_css_class == "even" ? "odd" : "even"
    end
%>
      <tr>
        <td><%= link_to daily_closing_price.share.name_isin, daily_closing_price.share %></td>
        <td><%= daily_closing_price.price %> <%=daily_closing_price.share.currency %></td>
        <td><%= daily_closing_price.date_of_day %></td>
        <td><%= link_to 'Show', daily_closing_price %></td>
        <td><%= link_to 'Edit', edit_daily_closing_price_path(daily_closing_price) %></td>
        <td><%= link_to 'Destroy', daily_closing_price, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= will_paginate @daily_closing_prices %>

<br>

<%= link_to 'New Daily closing price', new_daily_closing_price_path %>
<%= link_to 'New Daily closing prices', :controller => 'daily_closing_prices', :action => 'new_multiple' %>

app/views/daily_closing_prices/new.html.erb
<h1>New Daily Closing Price</h1>

<%= render 'form' %>

<%= link_to 'Back', daily_closing_prices_path %>

app/views/daily_closing_prices/new_multiple.html.erb
<h1>New daily_closing_prices</h1>

<%= form_tag(create_multiple_daily_closing_prices_path) do %>

	<table>
		<thead>
			<th>Share</th>
			<th>dailyClosingPrice</th>
		</thead>
		<tbody>
			<tr>
				<th><%= label_tag 'date[day]', 'When' %></th>
				<td><%= select_date(Time.now, :order => [:day, :month, :year]) %></td>
			</tr>
					
<% @daily_closing_prices.each_with_index do |daily_closing_price, index| %>
			<tr>
				<th><%= daily_closing_price.share.name_isin %></th>
	<%=  fields_for "daily_closing_prices[#{index}]", daily_closing_price do |f| %>
				<td><%=f.hidden_field :share_id %><%= f.text_field :price %></td>
	<% end %>
			</tr>
<% end %>
		</tbody>
	</table>

	<div class="actions">
		<%= submit_tag("Create all") %>
	</div>

<% end %>

	
<%= link_to 'Back', daily_closing_prices_path %>

app/views/daily_closing_prices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Share:</strong>
  <%= link_to @daily_closing_price.share.name_isin, @daily_closing_price.share %>
</p>

<p>
  <strong>Price:</strong>
  <%= @daily_closing_price.price %>
</p>

<p>
  <strong>Date of Day:</strong>
  <%= @daily_closing_price.date_of_day %>
</p>

<%= link_to 'Edit', edit_daily_closing_price_path(@daily_closing_price) %> |
<%= link_to 'Back', daily_closing_prices_path %>

app/views/daily_closing_prices/update_inline.html.erb
<span class="value"><%= number_to_currency @daily_closing_price.price %></span>
<div class="actions inline">
	<%= link_to "e", Rails.application.routes.url_helpers.edit_inline_daily_closing_price_path( @daily_closing_price.id ), :class => 'xhr inlineform edit' %>
</div>
<div class="info">
	<span class="daily_closing_price_change <%= css_class_for_daily_closing_price(@daily_closing_price.change_to_previous_absolute) %>" title="Veränderung zum Vortag: Absolut: <%= number_to_currency @daily_closing_price.change_to_previous_absolute, :unit => @daily_closing_price.share.currency %> | In Prozent: <%= number_to_percentage @daily_closing_price.change_to_previous_in_percent, :precision => 3 %>"></span>
</div>